# EncryptionService


### Health Check
# @name esHealthCheck
GET http://localhost:5000/health HTTP/1.1


### Encrypt Value
# @name esEncrypt
POST http://localhost:5000/api/v1/encrypt HTTP/1.1
content-type: application/json

{
    "value": "somevalue"
}

### Decrypt EncryptedValue
@esEncryptedValue = {{esEncrypt.response.body.value}}

# @name esDecrypt
POST http://localhost:5000/api/v1/decrypt HTTP/1.1
content-type: application/json

{
    "value":  "{{esEncryptedValue}}"
}

### Rotate EncryptionKey

# @name esRotateKey
POST http://localhost:5000/api/v1/rotateKey HTTP/1.1



# ApiGateway

### ApiGateway Health Check
# @name apigwHealthCheck
GET http://localhost:7000/health HTTP/1.1


### Encrypt Value
# @name apigwEncrypt
POST http://localhost:7000/encryption/encrypt HTTP/1.1
content-type: application/json

{
    "value": "somevalue"
}

### Decrypt EncryptedValue
@encryptedValue = {{apigwEncrypt.response.body.value}}

# @name apigwDecrypt
POST http://localhost:7000/encryption/decrypt HTTP/1.1
content-type: application/json

{
    "value":  "{{encryptedValue}}"
}

### Rotate EncryptionKey

# @name apigwRotateKey
POST http://localhost:7000/encryption/rotateKey HTTP/1.1